export const EXIT_CODES = {
  SUCCESS: 0,
  GENERAL_ERROR: 1,
  INVALID_CONFIGURATION: 2,
  AUTHENTICATION: 3,
  PROVIDER_NETWORK: 4,
  PARSING_ERROR: 5,
  SECRET_DETECTED: 6,
  INVALID_INPUT: 7,
  QUALITY_REVIEW: 8,
} as const;
